import type { Metadata } from "next";
import { Roboto_Mono } from 'next/font/google'
import './globals.css'

const montserrat = Roboto_Mono({
	variable: '--font-montserrat-sans',
	subsets: ['latin'],
	display: 'swap',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${montserrat.variable} antialiased`}>{children}</body>
		</html>
	)
}
